language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

branches:
  only:
  - master

script:
  - docker-compose up -d db
  - docker-compose run --rm api python manage.py test
