language: python
python:
  - "3.9"

services:
  - docker

branches:
  only:
  - master

before_script: docker-compose build

script:
  - docker-compose run --rm api python manage.py test

after_success: 
  - echo $CR_PAT | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
  - docker-compose push
