language: python
python:
  - "3.9"

services:
  - docker

before_install: pip install docker-compose

before_script:
  - docker-compose up -d --build

branches:
  only:
  - master

script:
  - docker-compose exec api python manage.py test
