version: '3'

services:
  api:
    container_name: roamium-api
    image: ghcr.io/gespyrop/roamium-api
    build:
      context: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 roamium.wsgi:application    
    env_file: .env
    volumes:
      - static_files:/roamium/static
      # - ./roamium:/roamium
    depends_on:
      - db

  db:
    container_name: roamium-db
    image: kartoza/postgis:12.0
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql

  nginx:
    container_name: roamium-nginx
    image: nginx:1.19.10-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_files:/www/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
    depends_on:
      - api
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'
  
volumes:
  db_data:
  static_files:
