version: '3'

services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    env_file: env/postgres.local
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file: env/postgres.local