version: '3'

services:
  api:
    container_name: roamium-api
    build:
      context: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 roamium.wsgi:application    
    env_file: env/api.local
    volumes:
      - static_files:/roamium/static
    depends_on:
      - db

  db:
    container_name: roamium-db
    image: kartoza/postgis:12.0
    env_file: env/postgres.local
    volumes:
      - db_data:/var/lib/postgresql

  nginx:
    container_name: roamium-nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_files:/www/static
    depends_on:
      - api
  
volumes:
  db_data:
  static_files:
