# Generated by Django 3.2.11 on 2022-01-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20210503_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_bike',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_family',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_friends',
        ),
        migrations.CreateModel(
            name='OSMPlace',
            fields=[
                ('osm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('wheelchair', models.CharField(blank=True, choices=[('no', 'No'), ('limited', 'Limited'), ('yes', 'Yes')], max_length=7, null=True)),
                ('categories', models.ManyToManyField(to='places.Category')),
            ],
            options={
                'verbose_name': 'OSM Place',
                'verbose_name_plural': 'OSM Places',
            },
        ),
    ]
