# Generated by Django 3.2.11 on 2022-04-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220115_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='wheelchair',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('limited', 'Limited'), ('yes', 'Yes')], max_length=7, null=True),
        ),
    ]
