# Generated by Django 3.2.11 on 2022-09-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_place_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmplace',
            name='osm_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
