# Generated by Django 3.2.13 on 2022-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='place_id',
            field=models.BigIntegerField(),
        ),
    ]
